<<<<<<< HEAD
DROP DATABASE IF EXISTS SLR_DB;
CREATE DATABASE SLR_DB;
USE SLR_DB;
=======
DROP DATABASE IF EXISTS slr_db;
CREATE DATABASE slr_db;
USE slr_db;

-- SELECT * FROM users;
-- SELECT * FROM posts;
-- SELECT * FROM userposts;
>>>>>>> c1b261de40c59389a0b1caa9ace0a1404d53294f
